server:
  port: 9025

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9020/eureka
    fetch-registry: true
    register-with-eureka: true
spring:

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  session:
    store-type: redis
  application:
    name: gradle-userservice
  rabbitmq:
    virtual-host: /
    username: root
    password: root
    host: 127.0.0.1
    port: 5672
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: facmc
      password: tecom
      database: facilityacmcdata
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/facilityACMCenter
    username: root
    password: root
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: false
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: false
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
    dbcp2:
      max-idle: 10
      initial-size: 5
#  security:
#    user:
#      name: admin
#      password: 706665237

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logback配置
logging:
  config: classpath:logback-spring.xml
  level:
    org.mybatis: debug
    mapper: debug
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN